### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by SidTheEngineer** [Stronkerton/cap2#1]
### Criteria 1: Table Creation (Migration File)
* _Score Level:_ 4/4
* _Comment(s):_ migration.js includes code that creates all tables with the appropriate structure and relationships (as defined in the spec).
 
### Criteria 2: Implementation of API Specification and Functionality
* _Score Level:_ 3/4
* _Comment(s):_ One noticeable thing I noticed was missing from the project that can keep functionality from working appropriately was the `cors` package (can be installed via `npm install --save cors`, then used via `app.use(cors())`). With this in place, functionality was pretty much spot on throughout the app, I didn't run into any major setbacks.
 
### Criteria 3: Test Case Results (Are all Test Cases Passing?)
* _Score Level:_ 4/4
* _Comment(s):_ All test cases are passing ✅ 
 
### Criteria 4: JavaScript and Express.js Fundamentals and Formatting
* _Score Level:_ 3.5
* _Comment(s):_ Overall great work with your JS! Fundamentals and formatting look solid throughout, errors are handled where they need to be throughout the routes, and language features are used appropriately. I have a couple of minor suggestions regarding best practices:

1. When declaring multiple variables, although using a comma and not using a variable keyword does work, it's often better to simply repeat the keyword (similar to how imports are usually done) for better readability and to prevent possible confusion that could come regarding reassignment:

```JavaScript
const variableOne = 1,
variableTwo = 2,
variableThree = 3
```

vs.

```JavaScript
const variableOne = 1
const variableTwo = 2
const variableThree = 3
```

2. When importing or requiring packages, it'e best to do so at the top of the file, before any other things are done in the code (check out the small example in `api.js`)
 
### Overall Score: 14.5/16 👏 
Nice job! Your project looks great from the code perspective and functionality is spot on. I mentioned a couple of small best practices above that will have this project pretty much perfect 👍

**Comment by Stronkerton** [comment]
Thank you!
